### ISSUE TITLE
Problem starting after installation

### ISSUE THREAD

**Issue by ZockerBoysHD** [chevereto/v4-docker-production#16]
I installed the docker version , used "make build" to create the images and now am trysing to start it with "make up"
everytime i try to start it tho i get this error:

https://screens.egopvp.com/files/2022/04/15/7mJRq.png

Any ideas?

**Comment by rodber** [comment]
Docker version.

**Comment by ZockerBoysHD** [comment]
Docker version 20.10.14, build a224086

**Comment by ZockerBoysHD** [comment]
ok just googled and 20.10.14 seems to be the latest one available for debian (which i run)

**Comment by MikePadge** [comment]
I just had this happen, the problem is in the Makefile, my environment expects there to be a dash between docker and compose

See Makefile line 90 for the up-d argument. 

changing 90 from `docker compose` to docker-compose` fixed the problem for me.

**Comment by rodber** [comment]
@ZockerBoysHD and @MikePadge 

It is mentioned on the `README.md` that this requires `docker compose` 2 as this is a brand new project I want to start with new stuff from scratch. The old "command" `docker-compose` is being changed by `docker compose` and you can read the why/how at [Compose V2](https://docs.docker.com/compose/cli-command/).

@ZockerBoysHD I had the same issue with Ubuntu 20.04 as it comes with 19.some. I had to remove it and manually install it following the instructions at Docker. I recommend you to install the software following [Docker Install on Debian](https://docs.docker.com/engine/install/debian/).

**Comment by ZockerBoysHD** [comment]
Installed Docker Compose 2.x and the "make prod" part is working now.

have set up my proxy and all but upon entering the chevereto page it always redirects me to "localhost/install"
 i havent found any hostname settings yet, where do i change stuff like this?

Also "make down" works but when starting again with "make up" it gives this error: 
https://screens.egopvp.com/files/2022/04/16/8N73v.png

**Comment by ZockerBoysHD** [comment]
ok well just when i wrote this my system finished "make prod" again.

I changed the projects/prod.yml file to includee "CHEVERETO_HOSTNAME: img.x.xxx"  on php - environments
and then started it using "make prod" and now its up and currently working on my hostname.

**Comment by MikePadge** [comment]
It might be worth it to put some CAPITAL FLAIR there in the readme to punctuate the difference between "docker compose" and "docker-compose". I use docker daily and this is actually the first I've heard of them making this change (I'm not a heavy docker desktop user). 

Checking my compose setup,
`docker-compose version`
Docker Compose version v2.3.4

I would just assume that I'm good here, but I don't have the new CE version installed with the `docker compose` separation.

**Comment by rodber** [comment]
@MikePadge That's the joy of using software. I had the same moment where I had to document myself on why there was two commands, turns out that I was using a Docker engine from 2019.

😉 I will link to the Docker docs so it is more straightforward.

**Comment by ZockerBoysHD** [comment]
so i now have a running version of chevereto v4.0  using docker on my system

my problems now aree that

1)
My API doesnt work at all. The public api key always says its invalid when uploading
My Private api key doesnt even generate (chv_***) and i cant regen it

2) i cant upload pictures at all it just loads and loads.

**Comment by ZockerBoysHD** [comment]
it also seems like it want to load my favicon from "localhost:14081" instead of the hostname....
![image](https://user-images.githubusercontent.com/30929430/163722172-e45e87c5-bb75-4a23-9714-4e3a62103b24.png)

**Comment by rodber** [comment]
We will handle this on our Support layer, to the same ticket you created. Not here at GitHub, this is exclusive for Technical issues on this particular project.
