### ISSUE TITLE
Getting an error running setup are per README

### ISSUE THREAD

**Issue by Filmtangent** [chevereto/v4-docker-production#21]
I'm getting an issue when following the instructions for building the docker image on a clean Ubuntu build:

``` 
👉 V4.0 local [PHP 8.1] (www-data)
unknown shorthand flag: 'p' in -p
See 'docker --help'.

....

<Docker help text>

make: *** [Makefile:86: up-d] Error 125```

not sure what I am doing wrong. I feel like maybe the generated docker file is faulty?

**Comment by rodber** [comment]
At [requirements](https://github.com/chevereto/v4-docker-production#requirements), it mentions that it requires [Compose V2](https://docs.docker.com/compose/cli-command/) docker compose.
